services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    hostname: jansenplex
    environment:
      TZ: 'America/Los_Angeles'
      PLEX_CLAIM: '{REDACTED}'  # Retrieve from https://www.plex.tv/claim
      ADVERTISE_IP: 'http://192.168.1.2:32400/'
      PLEX_UID: '109'  # unneeded if new setup
      PLEX_GID: '113'  # unneeded if new setup
      CHANGE_CONFIG_DIR_OWNERSHIP: false  # true if new setup, false if old make sure config volume ownership is PLEX_UID:PLEX_GID
    ports:
      - "32400:32400/tcp"  # needs to match local server remote port in settings, this one needs port forwarding
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - './config:/config'  # ownership needs to match PLEX_UID:PLEX_GID or be updated with CHANGE_CONFIG_DIR_OWNERSHIP. Must contain 'Library/Application Support/Plex Media Server/'
      - './transcode:/transcode'
      - type: bind  # if moving old server make sure the container path matches library settings. Need slave propagation to allow host mount to appear in container mount
        source: /media/ethan/MediaContent
        target: /media/ethan/MediaContent
        bind:
          propagation: slave
    restart: unless-stopped
